version: '3.1'

services:

  mongo:
    container_name: hex-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - hex-dbdata:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  hex-dbdata: